### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-front#2]
Let's release this addon to the world:

- [ ] Review/change/keep name
- [ ] check to ensure it's not tied to simple
- [ ] logo
- [ ] docs/readme
- [ ] review/complete tests
- [ ] release on packagist
- [ ] add to Statamic Marketplace

Relates to: https://github.com/transformstudios/simple-addon/issues/22

**Comment by adnankussair** [comment]
@edalzell Can this issue be closed? Did we decide not to release this and just keep it in simple?

**Comment by edalzell** [comment]
Too tied to our situation, at the moment.
